apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: valentine-tls
  namespace: valentine
spec:
  secretName: valentine-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: valentine.example.com
  dnsNames:
  - valentine.example.com
