apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valentine
  namespace: valentine
  annotations:
    argocd-image-updater.argoproj.io/image-list: valentine=slickg/valentine
    argocd-image-updater.argoproj.io/valentine.update-strategy: digest
    argocd-image-updater.argoproj.io/valentine.allow-tags: regexp:^latest$
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/ghvinerias/valentine.git
    targetRevision: main
    path: k8s
  destination:
    server: https://valentine.cloud.k8s.slick.ge
    namespace: valentine
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
